/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import pro.notifiy.server.jooq.tables.SendDetail;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SendDetailRecord extends UpdatableRecordImpl<SendDetailRecord> implements Record6<Long, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notify.send_detail.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>notify.send_detail.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notify.send_detail.app_id</code>.
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>notify.send_detail.app_id</code>.
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notify.send_detail.batch_id</code>.
     */
    public void setBatchId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>notify.send_detail.batch_id</code>.
     */
    public String getBatchId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>notify.send_detail.task_id</code>.
     */
    public void setTaskId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>notify.send_detail.task_id</code>.
     */
    public String getTaskId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notify.send_detail.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>notify.send_detail.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>notify.send_detail.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>notify.send_detail.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SendDetail.SEND_DETAIL.ID;
    }

    @Override
    public Field<String> field2() {
        return SendDetail.SEND_DETAIL.APP_ID;
    }

    @Override
    public Field<String> field3() {
        return SendDetail.SEND_DETAIL.BATCH_ID;
    }

    @Override
    public Field<String> field4() {
        return SendDetail.SEND_DETAIL.TASK_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SendDetail.SEND_DETAIL.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SendDetail.SEND_DETAIL.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAppId();
    }

    @Override
    public String component3() {
        return getBatchId();
    }

    @Override
    public String component4() {
        return getTaskId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAppId();
    }

    @Override
    public String value3() {
        return getBatchId();
    }

    @Override
    public String value4() {
        return getTaskId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    @Override
    public SendDetailRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SendDetailRecord value2(String value) {
        setAppId(value);
        return this;
    }

    @Override
    public SendDetailRecord value3(String value) {
        setBatchId(value);
        return this;
    }

    @Override
    public SendDetailRecord value4(String value) {
        setTaskId(value);
        return this;
    }

    @Override
    public SendDetailRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SendDetailRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public SendDetailRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SendDetailRecord
     */
    public SendDetailRecord() {
        super(SendDetail.SEND_DETAIL);
    }

    /**
     * Create a detached, initialised SendDetailRecord
     */
    public SendDetailRecord(Long id, String appId, String batchId, String taskId, LocalDateTime createTime, LocalDateTime updateTime) {
        super(SendDetail.SEND_DETAIL);

        setId(id);
        setAppId(appId);
        setBatchId(batchId);
        setTaskId(taskId);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
