/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import pro.notifiy.server.jooq.tables.SendRequest;
import pro.notifiy.server.model.SendStatus;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SendRequestRecord extends UpdatableRecordImpl<SendRequestRecord> implements Record12<Long, String, String, String, String, String, String, SendStatus, LocalDateTime, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notify.send_request.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>notify.send_request.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notify.send_request.app_id</code>.
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>notify.send_request.app_id</code>.
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notify.send_request.batch_id</code>.
     */
    public void setBatchId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>notify.send_request.batch_id</code>.
     */
    public String getBatchId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>notify.send_request.template_code</code>.
     */
    public void setTemplateCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>notify.send_request.template_code</code>.
     */
    public String getTemplateCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notify.send_request.template_params</code>.
     */
    public void setTemplateParams(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>notify.send_request.template_params</code>.
     */
    public String getTemplateParams() {
        return (String) get(4);
    }

    /**
     * Setter for <code>notify.send_request.target_type</code>.
     */
    public void setTargetType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>notify.send_request.target_type</code>.
     */
    public String getTargetType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>notify.send_request.target_list</code>.
     */
    public void setTargetList(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>notify.send_request.target_list</code>.
     */
    public String getTargetList() {
        return (String) get(6);
    }

    /**
     * Setter for <code>notify.send_request.send_status</code>.
     */
    public void setSendStatus(SendStatus value) {
        set(7, value);
    }

    /**
     * Getter for <code>notify.send_request.send_status</code>.
     */
    public SendStatus getSendStatus() {
        return (SendStatus) get(7);
    }

    /**
     * Setter for <code>notify.send_request.send_time</code>.
     */
    public void setSendTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>notify.send_request.send_time</code>.
     */
    public LocalDateTime getSendTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>notify.send_request.send_result</code>.
     */
    public void setSendResult(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>notify.send_request.send_result</code>.
     */
    public String getSendResult() {
        return (String) get(9);
    }

    /**
     * Setter for <code>notify.send_request.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>notify.send_request.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>notify.send_request.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>notify.send_request.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, String, SendStatus, LocalDateTime, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, String, String, String, SendStatus, LocalDateTime, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SendRequest.SEND_REQUEST.ID;
    }

    @Override
    public Field<String> field2() {
        return SendRequest.SEND_REQUEST.APP_ID;
    }

    @Override
    public Field<String> field3() {
        return SendRequest.SEND_REQUEST.BATCH_ID;
    }

    @Override
    public Field<String> field4() {
        return SendRequest.SEND_REQUEST.TEMPLATE_CODE;
    }

    @Override
    public Field<String> field5() {
        return SendRequest.SEND_REQUEST.TEMPLATE_PARAMS;
    }

    @Override
    public Field<String> field6() {
        return SendRequest.SEND_REQUEST.TARGET_TYPE;
    }

    @Override
    public Field<String> field7() {
        return SendRequest.SEND_REQUEST.TARGET_LIST;
    }

    @Override
    public Field<SendStatus> field8() {
        return SendRequest.SEND_REQUEST.SEND_STATUS;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SendRequest.SEND_REQUEST.SEND_TIME;
    }

    @Override
    public Field<String> field10() {
        return SendRequest.SEND_REQUEST.SEND_RESULT;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return SendRequest.SEND_REQUEST.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return SendRequest.SEND_REQUEST.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAppId();
    }

    @Override
    public String component3() {
        return getBatchId();
    }

    @Override
    public String component4() {
        return getTemplateCode();
    }

    @Override
    public String component5() {
        return getTemplateParams();
    }

    @Override
    public String component6() {
        return getTargetType();
    }

    @Override
    public String component7() {
        return getTargetList();
    }

    @Override
    public SendStatus component8() {
        return getSendStatus();
    }

    @Override
    public LocalDateTime component9() {
        return getSendTime();
    }

    @Override
    public String component10() {
        return getSendResult();
    }

    @Override
    public LocalDateTime component11() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAppId();
    }

    @Override
    public String value3() {
        return getBatchId();
    }

    @Override
    public String value4() {
        return getTemplateCode();
    }

    @Override
    public String value5() {
        return getTemplateParams();
    }

    @Override
    public String value6() {
        return getTargetType();
    }

    @Override
    public String value7() {
        return getTargetList();
    }

    @Override
    public SendStatus value8() {
        return getSendStatus();
    }

    @Override
    public LocalDateTime value9() {
        return getSendTime();
    }

    @Override
    public String value10() {
        return getSendResult();
    }

    @Override
    public LocalDateTime value11() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdateTime();
    }

    @Override
    public SendRequestRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SendRequestRecord value2(String value) {
        setAppId(value);
        return this;
    }

    @Override
    public SendRequestRecord value3(String value) {
        setBatchId(value);
        return this;
    }

    @Override
    public SendRequestRecord value4(String value) {
        setTemplateCode(value);
        return this;
    }

    @Override
    public SendRequestRecord value5(String value) {
        setTemplateParams(value);
        return this;
    }

    @Override
    public SendRequestRecord value6(String value) {
        setTargetType(value);
        return this;
    }

    @Override
    public SendRequestRecord value7(String value) {
        setTargetList(value);
        return this;
    }

    @Override
    public SendRequestRecord value8(SendStatus value) {
        setSendStatus(value);
        return this;
    }

    @Override
    public SendRequestRecord value9(LocalDateTime value) {
        setSendTime(value);
        return this;
    }

    @Override
    public SendRequestRecord value10(String value) {
        setSendResult(value);
        return this;
    }

    @Override
    public SendRequestRecord value11(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SendRequestRecord value12(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public SendRequestRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, SendStatus value8, LocalDateTime value9, String value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SendRequestRecord
     */
    public SendRequestRecord() {
        super(SendRequest.SEND_REQUEST);
    }

    /**
     * Create a detached, initialised SendRequestRecord
     */
    public SendRequestRecord(Long id, String appId, String batchId, String templateCode, String templateParams, String targetType, String targetList, SendStatus sendStatus, LocalDateTime sendTime, String sendResult, LocalDateTime createTime, LocalDateTime updateTime) {
        super(SendRequest.SEND_REQUEST);

        setId(id);
        setAppId(appId);
        setBatchId(batchId);
        setTemplateCode(templateCode);
        setTemplateParams(templateParams);
        setTargetType(targetType);
        setTargetList(targetList);
        setSendStatus(sendStatus);
        setSendTime(sendTime);
        setSendResult(sendResult);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
