/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import pro.notifiy.server.jooq.tables.SmsCloudTemplate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsCloudTemplateRecord extends UpdatableRecordImpl<SmsCloudTemplateRecord> implements Record10<Long, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notify.sms_cloud_template.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.app_id</code>.
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.app_id</code>.
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.template_code</code>.
     */
    public void setTemplateCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.template_code</code>.
     */
    public String getTemplateCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.cloud_template_content</code>.
     */
    public void setCloudTemplateContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.cloud_template_content</code>.
     */
    public String getCloudTemplateContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.cloud_template_code</code>.
     */
    public void setCloudTemplateCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.cloud_template_code</code>.
     */
    public String getCloudTemplateCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.cloud_sign_name</code>.
     */
    public void setCloudSignName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.cloud_sign_name</code>.
     */
    public String getCloudSignName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.cloud_sign_code</code>.
     */
    public void setCloudSignCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.cloud_sign_code</code>.
     */
    public String getCloudSignCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.cloud_state</code>.
     */
    public void setCloudState(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.cloud_state</code>.
     */
    public String getCloudState() {
        return (String) get(7);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>notify.sms_cloud_template.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>notify.sms_cloud_template.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.ID;
    }

    @Override
    public Field<String> field2() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.APP_ID;
    }

    @Override
    public Field<String> field3() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.TEMPLATE_CODE;
    }

    @Override
    public Field<String> field4() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.CLOUD_TEMPLATE_CONTENT;
    }

    @Override
    public Field<String> field5() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.CLOUD_TEMPLATE_CODE;
    }

    @Override
    public Field<String> field6() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.CLOUD_SIGN_NAME;
    }

    @Override
    public Field<String> field7() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.CLOUD_SIGN_CODE;
    }

    @Override
    public Field<String> field8() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.CLOUD_STATE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return SmsCloudTemplate.SMS_CLOUD_TEMPLATE.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAppId();
    }

    @Override
    public String component3() {
        return getTemplateCode();
    }

    @Override
    public String component4() {
        return getCloudTemplateContent();
    }

    @Override
    public String component5() {
        return getCloudTemplateCode();
    }

    @Override
    public String component6() {
        return getCloudSignName();
    }

    @Override
    public String component7() {
        return getCloudSignCode();
    }

    @Override
    public String component8() {
        return getCloudState();
    }

    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAppId();
    }

    @Override
    public String value3() {
        return getTemplateCode();
    }

    @Override
    public String value4() {
        return getCloudTemplateContent();
    }

    @Override
    public String value5() {
        return getCloudTemplateCode();
    }

    @Override
    public String value6() {
        return getCloudSignName();
    }

    @Override
    public String value7() {
        return getCloudSignCode();
    }

    @Override
    public String value8() {
        return getCloudState();
    }

    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdateTime();
    }

    @Override
    public SmsCloudTemplateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value2(String value) {
        setAppId(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value3(String value) {
        setTemplateCode(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value4(String value) {
        setCloudTemplateContent(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value5(String value) {
        setCloudTemplateCode(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value6(String value) {
        setCloudSignName(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value7(String value) {
        setCloudSignCode(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value8(String value) {
        setCloudState(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord value10(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public SmsCloudTemplateRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmsCloudTemplateRecord
     */
    public SmsCloudTemplateRecord() {
        super(SmsCloudTemplate.SMS_CLOUD_TEMPLATE);
    }

    /**
     * Create a detached, initialised SmsCloudTemplateRecord
     */
    public SmsCloudTemplateRecord(Long id, String appId, String templateCode, String cloudTemplateContent, String cloudTemplateCode, String cloudSignName, String cloudSignCode, String cloudState, LocalDateTime createTime, LocalDateTime updateTime) {
        super(SmsCloudTemplate.SMS_CLOUD_TEMPLATE);

        setId(id);
        setAppId(appId);
        setTemplateCode(templateCode);
        setCloudTemplateContent(cloudTemplateContent);
        setCloudTemplateCode(cloudTemplateCode);
        setCloudSignName(cloudSignName);
        setCloudSignCode(cloudSignCode);
        setCloudState(cloudState);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
