/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import pro.notifiy.server.jooq.tables.SmsTemplate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsTemplateRecord extends UpdatableRecordImpl<SmsTemplateRecord> implements Record10<Long, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notify.sms_template.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>notify.sms_template.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notify.sms_template.app_id</code>.
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>notify.sms_template.app_id</code>.
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notify.sms_template.template_code</code>.
     */
    public void setTemplateCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>notify.sms_template.template_code</code>.
     */
    public String getTemplateCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>notify.sms_template.template_content</code>.
     */
    public void setTemplateContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>notify.sms_template.template_content</code>.
     */
    public String getTemplateContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notify.sms_template.sign_name</code>.
     */
    public void setSignName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>notify.sms_template.sign_name</code>.
     */
    public String getSignName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>notify.sms_template.default_params</code>.
     */
    public void setDefaultParams(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>notify.sms_template.default_params</code>.
     */
    public String getDefaultParams() {
        return (String) get(5);
    }

    /**
     * Setter for <code>notify.sms_template.ext_params</code>.
     */
    public void setExtParams(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>notify.sms_template.ext_params</code>.
     */
    public String getExtParams() {
        return (String) get(6);
    }

    /**
     * Setter for <code>notify.sms_template.state</code>.
     */
    public void setState(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>notify.sms_template.state</code>.
     */
    public String getState() {
        return (String) get(7);
    }

    /**
     * Setter for <code>notify.sms_template.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>notify.sms_template.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>notify.sms_template.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>notify.sms_template.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SmsTemplate.SMS_TEMPLATE.ID;
    }

    @Override
    public Field<String> field2() {
        return SmsTemplate.SMS_TEMPLATE.APP_ID;
    }

    @Override
    public Field<String> field3() {
        return SmsTemplate.SMS_TEMPLATE.TEMPLATE_CODE;
    }

    @Override
    public Field<String> field4() {
        return SmsTemplate.SMS_TEMPLATE.TEMPLATE_CONTENT;
    }

    @Override
    public Field<String> field5() {
        return SmsTemplate.SMS_TEMPLATE.SIGN_NAME;
    }

    @Override
    public Field<String> field6() {
        return SmsTemplate.SMS_TEMPLATE.DEFAULT_PARAMS;
    }

    @Override
    public Field<String> field7() {
        return SmsTemplate.SMS_TEMPLATE.EXT_PARAMS;
    }

    @Override
    public Field<String> field8() {
        return SmsTemplate.SMS_TEMPLATE.STATE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SmsTemplate.SMS_TEMPLATE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return SmsTemplate.SMS_TEMPLATE.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAppId();
    }

    @Override
    public String component3() {
        return getTemplateCode();
    }

    @Override
    public String component4() {
        return getTemplateContent();
    }

    @Override
    public String component5() {
        return getSignName();
    }

    @Override
    public String component6() {
        return getDefaultParams();
    }

    @Override
    public String component7() {
        return getExtParams();
    }

    @Override
    public String component8() {
        return getState();
    }

    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAppId();
    }

    @Override
    public String value3() {
        return getTemplateCode();
    }

    @Override
    public String value4() {
        return getTemplateContent();
    }

    @Override
    public String value5() {
        return getSignName();
    }

    @Override
    public String value6() {
        return getDefaultParams();
    }

    @Override
    public String value7() {
        return getExtParams();
    }

    @Override
    public String value8() {
        return getState();
    }

    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdateTime();
    }

    @Override
    public SmsTemplateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value2(String value) {
        setAppId(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value3(String value) {
        setTemplateCode(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value4(String value) {
        setTemplateContent(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value5(String value) {
        setSignName(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value6(String value) {
        setDefaultParams(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value7(String value) {
        setExtParams(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value8(String value) {
        setState(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SmsTemplateRecord value10(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public SmsTemplateRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmsTemplateRecord
     */
    public SmsTemplateRecord() {
        super(SmsTemplate.SMS_TEMPLATE);
    }

    /**
     * Create a detached, initialised SmsTemplateRecord
     */
    public SmsTemplateRecord(Long id, String appId, String templateCode, String templateContent, String signName, String defaultParams, String extParams, String state, LocalDateTime createTime, LocalDateTime updateTime) {
        super(SmsTemplate.SMS_TEMPLATE);

        setId(id);
        setAppId(appId);
        setTemplateCode(templateCode);
        setTemplateContent(templateContent);
        setSignName(signName);
        setDefaultParams(defaultParams);
        setExtParams(extParams);
        setState(state);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
