/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import pro.notifiy.server.jooq.tables.TemplateChannel;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateChannelRecord extends UpdatableRecordImpl<TemplateChannelRecord> implements Record6<Long, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notify.template_channel.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>notify.template_channel.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notify.template_channel.app_id</code>.
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>notify.template_channel.app_id</code>.
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notify.template_channel.template_code</code>.
     */
    public void setTemplateCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>notify.template_channel.template_code</code>.
     */
    public String getTemplateCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>notify.template_channel.channel_code</code>.
     */
    public void setChannelCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>notify.template_channel.channel_code</code>.
     */
    public String getChannelCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>notify.template_channel.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>notify.template_channel.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>notify.template_channel.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>notify.template_channel.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TemplateChannel.TEMPLATE_CHANNEL.ID;
    }

    @Override
    public Field<String> field2() {
        return TemplateChannel.TEMPLATE_CHANNEL.APP_ID;
    }

    @Override
    public Field<String> field3() {
        return TemplateChannel.TEMPLATE_CHANNEL.TEMPLATE_CODE;
    }

    @Override
    public Field<String> field4() {
        return TemplateChannel.TEMPLATE_CHANNEL.CHANNEL_CODE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TemplateChannel.TEMPLATE_CHANNEL.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TemplateChannel.TEMPLATE_CHANNEL.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAppId();
    }

    @Override
    public String component3() {
        return getTemplateCode();
    }

    @Override
    public String component4() {
        return getChannelCode();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAppId();
    }

    @Override
    public String value3() {
        return getTemplateCode();
    }

    @Override
    public String value4() {
        return getChannelCode();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    @Override
    public TemplateChannelRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TemplateChannelRecord value2(String value) {
        setAppId(value);
        return this;
    }

    @Override
    public TemplateChannelRecord value3(String value) {
        setTemplateCode(value);
        return this;
    }

    @Override
    public TemplateChannelRecord value4(String value) {
        setChannelCode(value);
        return this;
    }

    @Override
    public TemplateChannelRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TemplateChannelRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TemplateChannelRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemplateChannelRecord
     */
    public TemplateChannelRecord() {
        super(TemplateChannel.TEMPLATE_CHANNEL);
    }

    /**
     * Create a detached, initialised TemplateChannelRecord
     */
    public TemplateChannelRecord(Long id, String appId, String templateCode, String channelCode, LocalDateTime createTime, LocalDateTime updateTime) {
        super(TemplateChannel.TEMPLATE_CHANNEL);

        setId(id);
        setAppId(appId);
        setTemplateCode(templateCode);
        setChannelCode(channelCode);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
