/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pro.notifiy.server.jooq.Keys;
import pro.notifiy.server.jooq.Notify;
import pro.notifiy.server.jooq.tables.records.CorpWxTemplateRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorpWxTemplate extends TableImpl<CorpWxTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>notify.corp_wx_template</code>
     */
    public static final CorpWxTemplate CORP_WX_TEMPLATE = new CorpWxTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CorpWxTemplateRecord> getRecordType() {
        return CorpWxTemplateRecord.class;
    }

    /**
     * The column <code>notify.corp_wx_template.id</code>.
     */
    public final TableField<CorpWxTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>notify.corp_wx_template.app_id</code>.
     */
    public final TableField<CorpWxTemplateRecord, String> APP_ID = createField(DSL.name("app_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.corp_wx_template.template_code</code>.
     */
    public final TableField<CorpWxTemplateRecord, String> TEMPLATE_CODE = createField(DSL.name("template_code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.corp_wx_template.template_content</code>.
     */
    public final TableField<CorpWxTemplateRecord, String> TEMPLATE_CONTENT = createField(DSL.name("template_content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.corp_wx_template.default_params</code>.
     */
    public final TableField<CorpWxTemplateRecord, String> DEFAULT_PARAMS = createField(DSL.name("default_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.corp_wx_template.ext_params</code>.
     */
    public final TableField<CorpWxTemplateRecord, String> EXT_PARAMS = createField(DSL.name("ext_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.corp_wx_template.state</code>.
     */
    public final TableField<CorpWxTemplateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(10).nullable(false).defaultValue(DSL.inline("INIT", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>notify.corp_wx_template.create_time</code>.
     */
    public final TableField<CorpWxTemplateRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>notify.corp_wx_template.update_time</code>.
     */
    public final TableField<CorpWxTemplateRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private CorpWxTemplate(Name alias, Table<CorpWxTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private CorpWxTemplate(Name alias, Table<CorpWxTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>notify.corp_wx_template</code> table reference
     */
    public CorpWxTemplate(String alias) {
        this(DSL.name(alias), CORP_WX_TEMPLATE);
    }

    /**
     * Create an aliased <code>notify.corp_wx_template</code> table reference
     */
    public CorpWxTemplate(Name alias) {
        this(alias, CORP_WX_TEMPLATE);
    }

    /**
     * Create a <code>notify.corp_wx_template</code> table reference
     */
    public CorpWxTemplate() {
        this(DSL.name("corp_wx_template"), null);
    }

    public <O extends Record> CorpWxTemplate(Table<O> child, ForeignKey<O, CorpWxTemplateRecord> key) {
        super(child, key, CORP_WX_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return Notify.NOTIFY;
    }

    @Override
    public Identity<CorpWxTemplateRecord, Long> getIdentity() {
        return (Identity<CorpWxTemplateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CorpWxTemplateRecord> getPrimaryKey() {
        return Keys.KEY_CORP_WX_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<CorpWxTemplateRecord>> getKeys() {
        return Arrays.<UniqueKey<CorpWxTemplateRecord>>asList(Keys.KEY_CORP_WX_TEMPLATE_PRIMARY, Keys.KEY_CORP_WX_TEMPLATE_TEMPLATE_CODE);
    }

    @Override
    public CorpWxTemplate as(String alias) {
        return new CorpWxTemplate(DSL.name(alias), this);
    }

    @Override
    public CorpWxTemplate as(Name alias) {
        return new CorpWxTemplate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CorpWxTemplate rename(String name) {
        return new CorpWxTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CorpWxTemplate rename(Name name) {
        return new CorpWxTemplate(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
