/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pro.notifiy.server.jooq.Keys;
import pro.notifiy.server.jooq.Notify;
import pro.notifiy.server.jooq.tables.records.FeishuBotTemplateRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeishuBotTemplate extends TableImpl<FeishuBotTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>notify.feishu_bot_template</code>
     */
    public static final FeishuBotTemplate FEISHU_BOT_TEMPLATE = new FeishuBotTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeishuBotTemplateRecord> getRecordType() {
        return FeishuBotTemplateRecord.class;
    }

    /**
     * The column <code>notify.feishu_bot_template.id</code>.
     */
    public final TableField<FeishuBotTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>notify.feishu_bot_template.app_id</code>.
     */
    public final TableField<FeishuBotTemplateRecord, String> APP_ID = createField(DSL.name("app_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.feishu_bot_template.template_code</code>.
     */
    public final TableField<FeishuBotTemplateRecord, String> TEMPLATE_CODE = createField(DSL.name("template_code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.feishu_bot_template.template_content</code>.
     */
    public final TableField<FeishuBotTemplateRecord, String> TEMPLATE_CONTENT = createField(DSL.name("template_content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.feishu_bot_template.default_params</code>.
     */
    public final TableField<FeishuBotTemplateRecord, String> DEFAULT_PARAMS = createField(DSL.name("default_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.feishu_bot_template.ext_params</code>.
     */
    public final TableField<FeishuBotTemplateRecord, String> EXT_PARAMS = createField(DSL.name("ext_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.feishu_bot_template.state</code>.
     */
    public final TableField<FeishuBotTemplateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(10).nullable(false).defaultValue(DSL.inline("INIT", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>notify.feishu_bot_template.create_time</code>.
     */
    public final TableField<FeishuBotTemplateRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>notify.feishu_bot_template.update_time</code>.
     */
    public final TableField<FeishuBotTemplateRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private FeishuBotTemplate(Name alias, Table<FeishuBotTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeishuBotTemplate(Name alias, Table<FeishuBotTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>notify.feishu_bot_template</code> table reference
     */
    public FeishuBotTemplate(String alias) {
        this(DSL.name(alias), FEISHU_BOT_TEMPLATE);
    }

    /**
     * Create an aliased <code>notify.feishu_bot_template</code> table reference
     */
    public FeishuBotTemplate(Name alias) {
        this(alias, FEISHU_BOT_TEMPLATE);
    }

    /**
     * Create a <code>notify.feishu_bot_template</code> table reference
     */
    public FeishuBotTemplate() {
        this(DSL.name("feishu_bot_template"), null);
    }

    public <O extends Record> FeishuBotTemplate(Table<O> child, ForeignKey<O, FeishuBotTemplateRecord> key) {
        super(child, key, FEISHU_BOT_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return Notify.NOTIFY;
    }

    @Override
    public Identity<FeishuBotTemplateRecord, Long> getIdentity() {
        return (Identity<FeishuBotTemplateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FeishuBotTemplateRecord> getPrimaryKey() {
        return Keys.KEY_FEISHU_BOT_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeishuBotTemplateRecord>> getKeys() {
        return Arrays.<UniqueKey<FeishuBotTemplateRecord>>asList(Keys.KEY_FEISHU_BOT_TEMPLATE_PRIMARY, Keys.KEY_FEISHU_BOT_TEMPLATE_TEMPLATE_CODE);
    }

    @Override
    public FeishuBotTemplate as(String alias) {
        return new FeishuBotTemplate(DSL.name(alias), this);
    }

    @Override
    public FeishuBotTemplate as(Name alias) {
        return new FeishuBotTemplate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeishuBotTemplate rename(String name) {
        return new FeishuBotTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeishuBotTemplate rename(Name name) {
        return new FeishuBotTemplate(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
