/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pro.notifiy.server.jooq.Keys;
import pro.notifiy.server.jooq.Notify;
import pro.notifiy.server.jooq.tables.records.PushTemplateRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PushTemplate extends TableImpl<PushTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>notify.push_template</code>
     */
    public static final PushTemplate PUSH_TEMPLATE = new PushTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PushTemplateRecord> getRecordType() {
        return PushTemplateRecord.class;
    }

    /**
     * The column <code>notify.push_template.id</code>.
     */
    public final TableField<PushTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>notify.push_template.app_id</code>.
     */
    public final TableField<PushTemplateRecord, String> APP_ID = createField(DSL.name("app_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.push_template.template_code</code>.
     */
    public final TableField<PushTemplateRecord, String> TEMPLATE_CODE = createField(DSL.name("template_code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.push_template.template_content</code>.
     */
    public final TableField<PushTemplateRecord, String> TEMPLATE_CONTENT = createField(DSL.name("template_content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.push_template.default_params</code>.
     */
    public final TableField<PushTemplateRecord, String> DEFAULT_PARAMS = createField(DSL.name("default_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.push_template.ext_params</code>.
     */
    public final TableField<PushTemplateRecord, String> EXT_PARAMS = createField(DSL.name("ext_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.push_template.state</code>.
     */
    public final TableField<PushTemplateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(10).nullable(false).defaultValue(DSL.inline("INIT", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>notify.push_template.create_time</code>.
     */
    public final TableField<PushTemplateRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>notify.push_template.update_time</code>.
     */
    public final TableField<PushTemplateRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private PushTemplate(Name alias, Table<PushTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private PushTemplate(Name alias, Table<PushTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>notify.push_template</code> table reference
     */
    public PushTemplate(String alias) {
        this(DSL.name(alias), PUSH_TEMPLATE);
    }

    /**
     * Create an aliased <code>notify.push_template</code> table reference
     */
    public PushTemplate(Name alias) {
        this(alias, PUSH_TEMPLATE);
    }

    /**
     * Create a <code>notify.push_template</code> table reference
     */
    public PushTemplate() {
        this(DSL.name("push_template"), null);
    }

    public <O extends Record> PushTemplate(Table<O> child, ForeignKey<O, PushTemplateRecord> key) {
        super(child, key, PUSH_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return Notify.NOTIFY;
    }

    @Override
    public Identity<PushTemplateRecord, Long> getIdentity() {
        return (Identity<PushTemplateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PushTemplateRecord> getPrimaryKey() {
        return Keys.KEY_PUSH_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<PushTemplateRecord>> getKeys() {
        return Arrays.<UniqueKey<PushTemplateRecord>>asList(Keys.KEY_PUSH_TEMPLATE_PRIMARY, Keys.KEY_PUSH_TEMPLATE_TEMPLATE_CODE);
    }

    @Override
    public PushTemplate as(String alias) {
        return new PushTemplate(DSL.name(alias), this);
    }

    @Override
    public PushTemplate as(Name alias) {
        return new PushTemplate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PushTemplate rename(String name) {
        return new PushTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PushTemplate rename(Name name) {
        return new PushTemplate(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
