/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pro.notifiy.server.jooq.Keys;
import pro.notifiy.server.jooq.Notify;
import pro.notifiy.server.jooq.tables.records.SendDetailRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SendDetail extends TableImpl<SendDetailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>notify.send_detail</code>
     */
    public static final SendDetail SEND_DETAIL = new SendDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SendDetailRecord> getRecordType() {
        return SendDetailRecord.class;
    }

    /**
     * The column <code>notify.send_detail.id</code>.
     */
    public final TableField<SendDetailRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>notify.send_detail.app_id</code>.
     */
    public final TableField<SendDetailRecord, String> APP_ID = createField(DSL.name("app_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.send_detail.batch_id</code>.
     */
    public final TableField<SendDetailRecord, String> BATCH_ID = createField(DSL.name("batch_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.send_detail.task_id</code>.
     */
    public final TableField<SendDetailRecord, String> TASK_ID = createField(DSL.name("task_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.send_detail.create_time</code>.
     */
    public final TableField<SendDetailRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>notify.send_detail.update_time</code>.
     */
    public final TableField<SendDetailRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private SendDetail(Name alias, Table<SendDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private SendDetail(Name alias, Table<SendDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>notify.send_detail</code> table reference
     */
    public SendDetail(String alias) {
        this(DSL.name(alias), SEND_DETAIL);
    }

    /**
     * Create an aliased <code>notify.send_detail</code> table reference
     */
    public SendDetail(Name alias) {
        this(alias, SEND_DETAIL);
    }

    /**
     * Create a <code>notify.send_detail</code> table reference
     */
    public SendDetail() {
        this(DSL.name("send_detail"), null);
    }

    public <O extends Record> SendDetail(Table<O> child, ForeignKey<O, SendDetailRecord> key) {
        super(child, key, SEND_DETAIL);
    }

    @Override
    public Schema getSchema() {
        return Notify.NOTIFY;
    }

    @Override
    public Identity<SendDetailRecord, Long> getIdentity() {
        return (Identity<SendDetailRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SendDetailRecord> getPrimaryKey() {
        return Keys.KEY_SEND_DETAIL_PRIMARY;
    }

    @Override
    public List<UniqueKey<SendDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<SendDetailRecord>>asList(Keys.KEY_SEND_DETAIL_PRIMARY);
    }

    @Override
    public SendDetail as(String alias) {
        return new SendDetail(DSL.name(alias), this);
    }

    @Override
    public SendDetail as(Name alias) {
        return new SendDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SendDetail rename(String name) {
        return new SendDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SendDetail rename(Name name) {
        return new SendDetail(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
