/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import pro.notifiy.server.jooq.Keys;
import pro.notifiy.server.jooq.Notify;
import pro.notifiy.server.jooq.tables.records.WxOffiaccountTemplateRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WxOffiaccountTemplate extends TableImpl<WxOffiaccountTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>notify.wx_offiaccount_template</code>
     */
    public static final WxOffiaccountTemplate WX_OFFIACCOUNT_TEMPLATE = new WxOffiaccountTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WxOffiaccountTemplateRecord> getRecordType() {
        return WxOffiaccountTemplateRecord.class;
    }

    /**
     * The column <code>notify.wx_offiaccount_template.id</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.app_id</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, String> APP_ID = createField(DSL.name("app_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.template_code</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, String> TEMPLATE_CODE = createField(DSL.name("template_code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.template_content</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, String> TEMPLATE_CONTENT = createField(DSL.name("template_content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.default_params</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, String> DEFAULT_PARAMS = createField(DSL.name("default_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.ext_params</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, String> EXT_PARAMS = createField(DSL.name("ext_params"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.state</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(10).nullable(false).defaultValue(DSL.inline("INIT", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.create_time</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>notify.wx_offiaccount_template.update_time</code>.
     */
    public final TableField<WxOffiaccountTemplateRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private WxOffiaccountTemplate(Name alias, Table<WxOffiaccountTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private WxOffiaccountTemplate(Name alias, Table<WxOffiaccountTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>notify.wx_offiaccount_template</code> table reference
     */
    public WxOffiaccountTemplate(String alias) {
        this(DSL.name(alias), WX_OFFIACCOUNT_TEMPLATE);
    }

    /**
     * Create an aliased <code>notify.wx_offiaccount_template</code> table reference
     */
    public WxOffiaccountTemplate(Name alias) {
        this(alias, WX_OFFIACCOUNT_TEMPLATE);
    }

    /**
     * Create a <code>notify.wx_offiaccount_template</code> table reference
     */
    public WxOffiaccountTemplate() {
        this(DSL.name("wx_offiaccount_template"), null);
    }

    public <O extends Record> WxOffiaccountTemplate(Table<O> child, ForeignKey<O, WxOffiaccountTemplateRecord> key) {
        super(child, key, WX_OFFIACCOUNT_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return Notify.NOTIFY;
    }

    @Override
    public Identity<WxOffiaccountTemplateRecord, Long> getIdentity() {
        return (Identity<WxOffiaccountTemplateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<WxOffiaccountTemplateRecord> getPrimaryKey() {
        return Keys.KEY_WX_OFFIACCOUNT_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<WxOffiaccountTemplateRecord>> getKeys() {
        return Arrays.<UniqueKey<WxOffiaccountTemplateRecord>>asList(Keys.KEY_WX_OFFIACCOUNT_TEMPLATE_PRIMARY, Keys.KEY_WX_OFFIACCOUNT_TEMPLATE_TEMPLATE_CODE);
    }

    @Override
    public WxOffiaccountTemplate as(String alias) {
        return new WxOffiaccountTemplate(DSL.name(alias), this);
    }

    @Override
    public WxOffiaccountTemplate as(Name alias) {
        return new WxOffiaccountTemplate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WxOffiaccountTemplate rename(String name) {
        return new WxOffiaccountTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WxOffiaccountTemplate rename(Name name) {
        return new WxOffiaccountTemplate(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
