/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import pro.notifiy.server.jooq.tables.Department;
import pro.notifiy.server.jooq.tables.Employee;
import pro.notifiy.server.jooq.tables.records.DepartmentRecord;
import pro.notifiy.server.jooq.tables.records.EmployeeRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * notify.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DepartmentRecord> KEY_DEPARTMENT_PRIMARY = Internal.createUniqueKey(Department.DEPARTMENT, DSL.name("KEY_department_PRIMARY"), new TableField[] { Department.DEPARTMENT.ID }, true);
    public static final UniqueKey<EmployeeRecord> KEY_EMPLOYEE_PRIMARY = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("KEY_employee_PRIMARY"), new TableField[] { Employee.EMPLOYEE.ID }, true);
}
