/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pro.notifiy.server.jooq.tables.Department;
import pro.notifiy.server.jooq.tables.Employee;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notify extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>notify</code>
     */
    public static final Notify NOTIFY = new Notify();

    /**
     * The table <code>notify.department</code>.
     */
    public final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>notify.employee</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * No further instances allowed
     */
    private Notify() {
        super("notify", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Department.DEPARTMENT,
            Employee.EMPLOYEE);
    }
}
