/*
 * This file is generated by jOOQ.
 */
package pro.notifiy.server.jooq;


import pro.notifiy.server.jooq.tables.Department;
import pro.notifiy.server.jooq.tables.Employee;


/**
 * Convenience access to all tables in notify.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>notify.department</code>.
     */
    public static final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>notify.employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;
}
